### ISSUE TITLE
Alingsås kommun öppna data - feedback

### ISSUE THREAD

**Issue by salgo60** [dpriskorn/svenska-grillplatser#18]
cc: [gis@alingsas.se](mailto:gis@alingsas.se)

* enl. #1 så Är Alingsås kommun **bäst i klassen**

Nedan lite tankar om den fil jag "hittade"

1. [ ] 1. skriv gärna i filen kontaktperson
2. [ ] 2. licensen för ert data är otydlig ange den som
3. [ ] 3. har ni ett schema eller spec ange detta i datat jmf #3
4. [ ] 4. ni använder EPSG:3007 mycket bättre med [WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System) nu sitter jag ch konverterar på [rl.se/utm](https://rl.se/utm)
5. [ ] 5. finns ni på GITHUB om inte skulle det underlätta
     1. [ ] jag har med i [EntitySchema:E408](https://www.wikidata.org/wiki/EntitySchema:E408) [Property:P1401](https://www.wikidata.org/wiki/Property:P1401) - Issue tracker URL vore snyggt att det fanns för varje grillplats...
6. [ ] 6. ni verkar ha unika id:n bra om ni beskriver detta se utmaningar vi har nu att se [när vi skall matcha Wikidata och grillplatser.nu](https://github.com/dpriskorn/svenska-grillplatser/issues/2#issuecomment-1678677482) - ev. kommer DIGG att ta tag i detta med persistenta identifierare delta gärna där se [persistent-identifiers-investigation](https://github.com/diggsweden/persistent-identifiers-investigation/issues/12)
7. [ ] 7. API till ert data? jmf hur jag jobbar med Nobelprize.org och kollar deras data [Notebook](https://github.com/salgo60/open-data-examples/blob/master/Nobel%20API_2_1.ipynb) / [blog post](https://github.com/salgo60/NOSAD-POC-Wikidata/issues/13) / [deras api](https://api.nobelprize.org/2.1/laureate/1011) hur vi kopplar ihop oss --> 1 minut efter priset delas ut finns kopplingarna på Wikipedia på sv/en/ru
8. [ ] 8. språk taggar saknas -  vore bra att stödja engelska namn pp grillplatser och dom vanligaste språken som pratas i er kommun
9. [ ] .....

**Comment by salgo60** [comment]
<img width="845" alt="image" src="https://github.com/dpriskorn/svenska-grillplatser/assets/14206509/ea61f584-9747-4690-9626-31e352cb71bb">

**Comment by salgo60** [comment]
**Pratade kort med Göran W och emailade honom länk till denna plats och sa att vi blir glada för dialog**

<img width="882" alt="image" src="https://github.com/dpriskorn/svenska-grillplatser/assets/14206509/28a5e481-58f1-49b2-b262-a0f220b0080d">

**Comment by salgo60** [comment]
<img width="858" alt="image" src="https://github.com/dpriskorn/svenska-grillplatser/assets/14206509/42bc694d-d12e-4603-a56c-10e9455264c6">
